# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundamentals_Data',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('market_capitalization', models.IntegerField()),
                ('outstanding_shares', models.IntegerField()),
            ],
        ),
    ]
